# -*- coding: utf-8 -*-
"""2NXT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-zjLHYtS0cm0kSzHlvIpkAp_Byf25X3s
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import scipy.stats as sst
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.feature_selection import f_classif, chi2, SelectKBest, SelectPercentile
from collections import Counter
from sklearn.model_selection import StratifiedKFold, train_test_split, cross_val_score
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, PrecisionRecallDisplay, precision_recall_curve, roc_curve, RocCurveDisplay, roc_auc_score, average_precision_score
from sklearn.decomposition import PCA

dataset = pd.read_csv('/content/drive/My Drive/Project5405/train_data.csv')
d2 = pd.read_csv('/content/drive/My Drive/Project5405/imp_feat.csv')


# imp = d2.iloc[:,1].tolist()[:50]
imp = d2.iloc[:,1].tolist()[:100]


# dataset = dataset.iloc[0:30000,:] ## remove this later

y = dataset.Label
X = dataset.drop(["Label","KIBA"],axis="columns")
X = dataset[imp]



# X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.5, stratify=y)#random_state=2)#,shuffle=True)#, 

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.07, stratify=y)#random_state=2)#,shuffle=True)#,

from xgboost import XGBClassifier, XGBRFClassifier
from sklearn.ensemble import StackingClassifier, AdaBoostClassifier, BaggingClassifier, ExtraTreesClassifier, GradientBoostingClassifier, HistGradientBoostingClassifier, VotingClassifier, RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import BaggingClassifier

y_train.replace({False: 0, True: 1}, inplace=True)
y_test.replace({False: 0, True: 1}, inplace=True)


xgb = XGBClassifier(use_label_encoder = False, max_depth = 8, learning_rate = 0.075, n_estimators = 450, scale_pos_weight = 1.5)# scale_pos_weight = 86324/23155)#, eval_metric = "error" #"logloss")#, max_depth =7)

lr = LogisticRegression()
sv = SVC(probability=True, kernel = "linear")
et = ExtraTreesClassifier()
dt = DecisionTreeClassifier(max_depth = 7)
knn = KNeighborsClassifier()
bg = BaggingClassifier()
rf = RandomForestClassifier(max_depth = 6)
mlp = MLPClassifier(max_iter=300)

models = [('xgb',xgb), ('et',et), ('dt',dt)]

# models = [('xgb',xgb), ('rf',rf)]

# models = [('xgb',xgb), ('sv',sv)] ##best precision but low recall

# models = [('xgb',xgb), ('sv',sv), ('et',et)] ## 2 hours and counting 


vc = VotingClassifier(estimators=models, voting="soft")

# vc = StackingClassifier(estimators=models, final_estimator= knn) 

# vc = StackingClassifier(estimators= [('xgb',xgb), ('et',et)], final_estimator= mlp) 

# vc = StackingClassifier(estimators= [('xgb',xgb), ('et',et)], final_estimator= bg) #bad
#performed good with final = dt .74 P

# vc = StackingClassifier(estimators= [('xgb',xgb)], final_estimator= et) #performed good with final = dt .74 P


## try blending



# vc = StackingClassifier(estimators= [('bg',bg), ('et',et)], final_estimator= xgb) #performed good with final = dt .74 P


# vc = StackingClassifier(estimators= [('xgb',xgb), ('et',et), ('svm',sv)])#, final_estimator= dt) 



# vc = StackingClassifier(estimators = [('dt',dt), ('et',et), ('svm',sv), ('knn',knn), ('mlp',mlp)], final_estimator= xgb) ## 0.59 PR

# vc = StackingClassifier(estimators = [('xgb',xgb), ('et',et), ('svm',sv), ('knn',knn), ('mlp',mlp)], final_estimator= dt)


#have tried using lr as final estimator


vc.fit(X_train,y_train)
# xgb.fit(X_train,y_train, eval_metric='aucpr')


# xgbrf = XGBRFClassifier()

# xgb.fit(X_train,y_train, eval_metric='map')

# kf = pd.DataFrame({'Variable':X.columns,
#               'Importance':xgb.feature_importances_}).sort_values('Importance', ascending=False)


# print(kf.to_csv("C:\\Users\\bhard\\OneDrive\\Desktop\\SYSC 5405 Pattern Classification\\Project\\imp_feat_xgb.csv"))

# xgbrf.fit(X_train,y_train)

# pred_y = xgb.predict(X_test)
# pred_y_prob = xgb.predict_proba(X_test)[:,1]


pred_y = vc.predict(X_test)
pred_y_prob = vc.predict_proba(X_test)[:,1]


cm = confusion_matrix(y_test,pred_y)
tn,fp,fn,tp = cm.ravel()

print("Accuracy: ",(tp+tn)/(tp+tn+fp+fn))
print("Precision: ", tp/(tp+fp))
print("Recall: ", tp/(tp+fn))
print("Sensitivity: ", tp/(tp+fn))
print("Specificity: ",tn/(tn+fp))
pr = tp/(tp+fp)
rc = tp/(tp+fn)
print("F1 score: ", (2*pr*rc)/(pr+rc))

PrecisionRecallDisplay.from_predictions(y_test,pred_y_prob,pos_label=1)
ConfusionMatrixDisplay.from_predictions(y_test,pred_y)   
RocCurveDisplay.from_predictions(y_test,pred_y_prob,pos_label=1)

