# -*- coding: utf-8 -*-
"""2NXT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-zjLHYtS0cm0kSzHlvIpkAp_Byf25X3s
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import scipy.stats as sst
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.feature_selection import f_classif, chi2, SelectKBest, SelectPercentile
from collections import Counter
from sklearn.model_selection import StratifiedKFold, train_test_split, cross_val_score
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, PrecisionRecallDisplay, precision_recall_curve, roc_curve, RocCurveDisplay, roc_auc_score, average_precision_score
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler

dataset = pd.read_csv('/content/drive/My Drive/Project5405/train_data.csv')
d2 = pd.read_csv('/content/drive/My Drive/Project5405/most_imp_feat_xgb.csv')


imp = d2.iloc[:,1].tolist()[:50]    #Can increase decrease later
# imp = d2.iloc[:,1].tolist()[:60]



# dataset = dataset.iloc[0:30000,:] ## remove this later

y = dataset.Label
X = dataset.drop(["Label","KIBA"],axis="columns")
X = dataset[imp]
X = MinMaxScaler().fit_transform(X)

# X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.5, stratify=y)#random_state=2)#,shuffle=True)#, 

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.074699, stratify=y, random_state=42)#,shuffle=True)#,



from xgboost import XGBClassifier, XGBRFClassifier
from sklearn.ensemble import StackingClassifier, AdaBoostClassifier, BaggingClassifier, ExtraTreesClassifier, GradientBoostingClassifier, HistGradientBoostingClassifier, VotingClassifier, RandomForestClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.calibration import CalibratedClassifierCV
from sklearn.linear_model import SGDClassifier



y_train.replace({False: 0, True: 1}, inplace=True)
y_test.replace({False: 0, True: 1}, inplace=True)


xgb = XGBClassifier(use_label_encoder = False, max_depth = 20, learning_rate = 0.075, n_estimators = 450,random_state= 42, scale_pos_weight = 1.5)# scale_pos_weight = 86324/23155)#, eval_metric = "error" #"logloss")#, max_depth =7)
# xgb = XGBClassifier()

lr = LogisticRegression(max_iter=1000, solver='saga')##can update max_iter, solver = saga
## https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

sv = SVC(probability=True)
sv2 = LinearSVC() 
et = ExtraTreesClassifier(n_estimators=150, max_features="log2", min_samples_split=5, random_state= 42)
dt = DecisionTreeClassifier(max_depth = 7)
knn = KNeighborsClassifier(n_neighbors=9)
bg = BaggingClassifier(DecisionTreeClassifier(max_depth = 7), n_estimators=500, max_samples=100, bootstrap=True, n_jobs=-1)
rf = RandomForestClassifier(max_depth = 6, n_estimators=500, max_leaf_nodes=10, n_jobs=-1)
mlp = MLPClassifier(max_iter=300)
svm_sgd = CalibratedClassifierCV(SGDClassifier(max_iter=1000, tol=1e-3, loss = 'hinge'))
lr_sgd = CalibratedClassifierCV(SGDClassifier(max_iter=1000, tol=1e-3, loss = 'log',random_state= 42))


# models = [('et',et), ('sv',sv)]
# # models = [('rf',rf), ('sv',sv), ('lr',lr)]   ## try next 
# models = [('bg',bg), ('sv',sv)]  # ('rf',rf)]   ## try next



##compare rf with et
## adaboost

# models = [('rf',rf),('xgb'],xgb)   ## try next (better than bagging classifier)

#also try rf
# models = [('et',et)]#, ('qt',qt)]   ## try next (better than bagging classifier)



# models = [('xgb',xgb),('lr',lr)] ## wow
#What about rf and xgb
# models = [('xgb',xgb),('rf',rf)]#, ('dt',dt)]
# models = [('xgb',xgb),('lr',lr),('et',et)] ## wow pr 0.889
# models = [('xgb',xgb),('lr',lr),('et',et)] ## wow pr 0.889    
## not good with ('mlp',mlp)

##,('mlp',mlp),('knn',knn)] 


# models = [('xgb',xgb), ('et',et)]   ## voting metric = // stacking metric


models = [('xgb',xgb),('et',et),('svm_sgd',svm_sgd)]   ##best combination so far as of 1st december 10.45 am with pr@50 0.8530571992110454



# models = [('svm_sgd',svm_sgd)]  ## PR@50Recall = 0.4362077660110943

# models = [('dt',dt)] ## PR@50Recall = 0.4448409134916567

# models = [('lr_sgd',lr_sgd),('svm_sgd',svm_sgd) ] ## PR@50Recall = 0.4379746835443038
# models = [('lr_sgd',lr_sgd),('svm_sgd',svm_sgd),('dt',dt),('mlp',mlp) ] ## PR@50Recall =


# models = [('dt',dt), ('svm_sgd',svm_sgd)] ## PR@50Recall = 0.4643048845947397

# models = [('xgb',xgb)] 

# models = [('et',et)]

# models = [('xgb',xgb), ('sv',sv)] ##best precision but low recall ## need diverse weak leaners

# models = [('xgb',xgb), ('sv',sv), ('et',et)] ## 2 hours and counting 


# models = [('et',et)]

vc = VotingClassifier(estimators=models, voting="soft")

# vc = StackingClassifier(estimators = models, final_estimator = svm_sgd)   ## PR@50Recall = 



# vc = StackingClassifier(estimators = models, final_estimator = svm_sgd)   ## PR@50Recall = 0.76 with models = et only


# vc = StackingClassifier(estimators = models, final_estimator = mlp)   ## PR@50Recall = 


# vc = StackingClassifier(estimators= [('xgb',xgb), ('et',et)], final_estimator= mlp) 

# vc = StackingClassifier(estimators= [('xgb',xgb), ('et',et)], final_estimator= bg) #bad
#performed good with final = dt .74 P

# vc = StackingClassifier(estimators= [('xgb',xgb)], final_estimator= et) #performed good with final = dt .74 P


## try blending



# vc = StackingClassifier(estimators= [('bg',bg), ('et',et)], final_estimator= xgb) #performed good with final = dt .74 P


# vc = StackingClassifier(estimators= [('xgb',xgb), ('et',et), ('svm',sv)])#, final_estimator= dt) 



# vc = StackingClassifier(estimators = [('dt',dt), ('et',et), ('svm',sv), ('knn',knn), ('mlp',mlp)], final_estimator= xgb) ## 0.59 PR

# vc = StackingClassifier(estimators = [('xgb',xgb), ('et',et), ('svm',sv), ('knn',knn), ('mlp',mlp)], final_estimator= dt)


#have tried using lr as final estimator


vc.fit(X_train,y_train)
# xgb.fit(X_train,y_train, eval_metric='aucpr')


# xgbrf = XGBRFClassifier()

# xgb.fit(X_train,y_train, eval_metric='map')

# kf = pd.DataFrame({'Variable':X.columns,
#               'Importance':xgb.feature_importances_}).sort_values('Importance', ascending=False)


# print(kf.to_csv("C:\\Users\\bhard\\OneDrive\\Desktop\\SYSC 5405 Pattern Classification\\Project\\imp_feat_xgb.csv"))

# xgbrf.fit(X_train,y_train)

# pred_y = xgb.predict(X_test)
# pred_y_prob = xgb.predict_proba(X_test)[:,1]


pred_y = vc.predict(X_test)
pred_y_prob = vc.predict_proba(X_test)[:,1]


cm = confusion_matrix(y_test,pred_y)
tn,fp,fn,tp = cm.ravel()

# print("Accuracy: ",(tp+tn)/(tp+tn+fp+fn))
# print("Precision: ", tp/(tp+fp))
# print("Recall: ", tp/(tp+fn))
# print("Sensitivity: ", tp/(tp+fn))
# print("Specificity: ",tn/(tn+fp))
# pr = tp/(tp+fp)
# rc = tp/(tp+fn)
# print("F1 score: ", (2*pr*rc)/(pr+rc))

# PrecisionRecallDisplay.from_predictions(y_test,pred_y_prob,pos_label=1)

precision, recall, thresholds = precision_recall_curve(y_test, pred_y_prob, pos_label=1)
precision_inv = precision[::-1]
recall_inv = recall[::-1]
pr_res = np.interp(0.5, recall_inv, precision_inv)
#pr_res = round(pr_res, 3)
print("PR Score:" + str(pr_res))

plt.figure()
plt.axvline(0.5, 0, color="black", linestyle="dotted")#, label="Recall=0.5")
plt.axhline(pr_res, 0, color="black", linestyle="dotted", label= "PR@50Recall: {0}".format(pr_res))
lw = 2
plt.plot(recall, precision, color="darkorange", lw=lw)#, label= "PR@50Recall: {0}".format(pr_res), )
# plt.plot([0, 1], [0.5, 0.5], color="navy", lw=lw, linestyle="--")
plt.xlim([0.0, 1.1])
plt.ylim([0.0, 1.1])
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision Recall Curve")
plt.legend(loc="lower right")



ConfusionMatrixDisplay.from_predictions(y_test,pred_y)   
RocCurveDisplay.from_predictions(y_test,pred_y_prob,pos_label=1)

